### PR TITLE
Improvements

### LINKED ISSUE #92: Resolved main thread issues
Make sure that all `networking.post` completions in [WMTOperationsImpl.swift](https://github.com/wultra/mtoken-sdk-ios/blob/develop/WultraMobileTokenSDK/Operations/Service/WMTOperationsImpl.swift) are call on main thread.

In some cases, it's called on the main thread, in other cases, there is just an assert which will throw an error during development.

### PR DESCRIPTION
**Pull request by kober32**
- Fixed #92  where not all callbacks were called on the main thread
- Unified API to return `Result` in completions
- Code cleanup
- Added swiftlint to the project build

### CODE REVIEW

**Review by petrdvorak — APPROVED** [review]
Approved

**Review by hvge — APPROVED** [review]
Looks OK, but I think that we should move responsibility for dispatching results to (main) queue to the networking library. It makes more sense to me will save us a lot of repetitive code.

I'll create a ticket for that.

**Comment by kober32** [comment]
> Looks OK, but I think that we should move responsibility for dispatching results to (main) queue to the networking library. It makes more sense to me will save us a lot of repetitive code.
> 
> I'll create a ticket for that.

Good point, I'll do that right away..

**Comment by kober32** [comment]
The main queue execution was moved to the networking library - https://github.com/wultra/networking-apple/pull/32

**Pull request merged**
