### PR TITLE
Operation expiration utility

### LINKED ISSUE #41: Add utility for operation expiring observation

### PR DESCRIPTION
**Pull request by kober32**
Resolve #41 

Added a utility class for watching the expiration of operations.
This is very handy as notifications are not always received and are unreliable sometimes.

Documentation and tests we're added for this feature as well.

### CODE REVIEW

**Review by hvge — CHANGES_REQUESTED** [review]
In general looks OK, but I think that the current `WMTOperationExpirationWatcher` implementation is a bit overkill. I think that the operation queue as a synchronization primitive is not wisely selected. The job we do in the thread safe context is such simple, that mutex would be enough.

**Comment by kober32** [comment]
OK, removed the `OperationQueue` and replaced by `DispatchSemaphore`

**Review by hvge — COMMENTED** [review]
I'm thinking whether we still need that callbacks in public methods, once the implementation is synchronous.

**Comment by kober32** [comment]
In the end, I made the API synchronous. It makes more sense this way..

**Review by hvge — APPROVED** [review]
Looks OK

**Pull request merged**
